name: 'Build, Lint, Test'

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Running tests
        run: npm run test
        working-directory: ../src
        timeout-minutes: 15

      - name: Running lint
        run: npm run lint
        working-directory: ../src
        timeout-minutes: 15